/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface GaugeCircle {
    'max': number;
    'size': number;
    'unit': string;
    'value': number;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLGaugeCircleElement extends Components.GaugeCircle, HTMLStencilElement {}
  var HTMLGaugeCircleElement: {
    prototype: HTMLGaugeCircleElement;
    new (): HTMLGaugeCircleElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'gauge-circle': HTMLGaugeCircleElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface GaugeCircle extends JSXBase.HTMLAttributes<HTMLGaugeCircleElement> {
    'max'?: number;
    'size'?: number;
    'unit'?: string;
    'value'?: number;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'gauge-circle': GaugeCircle;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


